### ISSUE TITLE
The UP button and the DOWN button have opposite functions

### ISSUE THREAD

**Issue by yeseQAQ** [srikit/mini-fm-radio-module#1]
I have made my own radio according to your circuit diagram and flashed the firmware, but in the process of test, I found that the functions of the UP button and the DOWN button in the tuning mode are contrary to your description. I checked my design to confirm my circuit is the same as yours, is this a BUG or mistake? (The firmware I use is _fm-receiver-module-firmware-18-04-2021A_, and the flash tool is STVP&ST-LINK)

**Comment by dilshan** [comment]
The new firmware button order changed and is not yet updated in the documentation.
